name: CI

on: [push, pull_request]

jobs:
  build:
    name: Rails unit tests with Postgres
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-    - name: Build and test with Rake
    - name: Run tests
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        sudo apt-get -yqq install libpq-dev libsqlite3-dev libmysqlclient-dev
        gem install bundler:1.17.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        cp test/dummy/config/database.postgresql.yml test/dummy/config/database.yml
        bundle exec rake db:create db:schema:load test
        bundle exec rake db:seed
